name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '32 3 * * 0'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: joschi/prosody-alpine:${{ github.sha }}
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.sha }}
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: joschi/prosody-alpine:${{ github.sha }}
          fail-build: false
          acs-report-enable: true
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
