name: Release
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: joschi/prosody-alpine
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          load: true
          push: false
          tags: joschi/prosody-alpine:${{ github.sha }}
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: joschi/prosody-alpine:${{ github.sha }}
          fail-build: false
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: joschi/prosody-alpine:${{ steps.vars.outputs.tag }}
